### ISSUE TITLE
Create birthday channel blacklist

### ISSUE THREAD

**Issue by polina-popova** [tolstoyevsky/hubot-happy-birthder#100]
Create an environmental variable BIRTHDAY_CHANNEL_BLACKLIST to exclude particular people from discussing someone's birthday.

**Comment by sibiryoff** [comment]
Just a suggestion: maybe, there should be a couple of commands for managing this list, like `birthday discuss add/exclude username`? So it will be possible not to involve, f.e., new company members in that discussions.
