### ISSUE TITLE
Fix language uniformity

### ISSUE THREAD

**Issue by sibiryoff** [tolstoyevsky/hubot-happy-birthder#19]
We have some output messages in russian language: https://github.com/tolstoyevsky/hubot-happy-birthder/blob/2f609650767d971764f2f9fda904861948767223/src/birthder.js#L209 and some in english: https://github.com/tolstoyevsky/hubot-happy-birthder/blob/2f609650767d971764f2f9fda904861948767223/src/birthder.js#L39.
So I suggest to choose one default language and fix messages text.

**Comment by eugulixes** [comment]
@ukhryab, split the issue into two different issues: getting rid of the mix of the languages and the multilanguage support (or simply remove the second one). The point is that it's quite difficult to close the issue because the multilanguage support is _indeed_ not the first priority.

**Comment by sibiryoff** [comment]
https://github.com/tolstoyevsky/hubot-happy-birthder/pull/25
