### ISSUE TITLE
birthdays list command is invoked only if the bot name is specified

### ISSUE THREAD

**Issue by TheSergeX** [tolstoyevsky/hubot-happy-birthder#28]
Other commands such as `birthday set`, `birthday on`, `birthday delete` don't have such problem.

**Comment by sibiryoff** [comment]
I don't think it's a bug, but we have to decide what to do with it.

**Comment by TheSergeX** [comment]
@ukhryab yes, this isn't a bug. but this is strange. We need to bring this to a common view.

**Comment by eugulixes** [comment]
@Sergei-vb @ukhryab, I suggest we will do vise versa: make all the command (from the script) to be invoked only if the bot name is specified.
