### ISSUE TITLE
Change birthdays list format

### ISSUE THREAD

**Issue by sibiryoff** [tolstoyevsky/hubot-happy-birthder#32]
I think, we should change the view of the birthday list. What we have now:

![bdays](https://user-images.githubusercontent.com/16405513/43524723-a2ab779e-95a8-11e8-932d-495cedad9dcf.png)

There's no sorting here, and year is redundant, 'cause the person who calls this command wants to know about upcoming birthdays, not born dates. So, I suggest, we should:

1. Sort this list by month&day;
2. Change this date format to DD.MM.

**Comment by eugulixes** [comment]
I partially agree.
> There's no sorting here

Indeed, we should order the list by names, for example.

> year is redundant, 'cause the person who calls this command wants to know about upcoming birthdays, not born dates.

Who knows... Probably the person who invokes the command wants to know if the upcoming birthday is anniversary. Maybe we have to make the command privileged to limit the number of people who are able to invoke the command and get to know the birth dates of every single employee in the company=)

**Comment by sibiryoff** [comment]
Just look at how it is in our current corporate messenger :)
Maybe, there should be different commands for upcoming birthdays and birth dates.

**Comment by eugulixes** [comment]
> Maybe, there should be different commands for upcoming birthdays and birth dates.

Maybe. I would really like to hear the views of other people.
@HackoDev, @Sergei-vb.

**Comment by eugulixes** [comment]
I guess we have to speed up the process. I interviewed the members of our team offline and they voted unanimously in favour of the format `dd.mm`.

**Comment by eugulixes** [comment]
Ok, the date format was changed (see #58). What about sorting? I guess there should be a separate issue for it.

**Comment by sibiryoff** [comment]
Closed in favor of https://github.com/tolstoyevsky/hubot-happy-birthder/issues/64
