### ISSUE TITLE
Regular expression improving

### ISSUE THREAD

**Issue by KvaziProton** [tolstoyevsky/hubot-happy-birthder#67]
Suggestions on improving regular expression from hubot-happy-birthder:
Username `/(?:@?([\w\d .\-_]+)\?*)/`
- decide should question mark be an optional ending of username or better include it in list of valid simbols
- if hyphen is in the beggining of symbol class it is possible to avoid slash before
- keep in mind that `\w` is equvalent to [A-Za-z0-9] so digits already included
so in result we can use `(?:@?([-\w ._?]+))` instead

**Comment by polina-popova** [comment]
It looks like RocketChat accepts any symbols in username, so it is possible to cut regular expression to `(?:@?(.+))`. But in that case we should add trim function to name extraction:
`name = msg.match[2].trim()`

**Comment by sibiryoff** [comment]
How have you concluded that RocketChat accepts any symbols in username? I have not succeed in using `?`, `!`, `#` in username:

![username](https://user-images.githubusercontent.com/16405513/45222305-da3fa500-b2bc-11e8-9318-d9ed54b0dbc2.png)

**Comment by eugulixes** [comment]
@ukhryab, you are right. I haven't found clear restrictions in the official documentation, but found the [original regex](https://github.com/RocketChat/Rocket.Chat/blob/0.69.1/packages/rocketchat-lib/server/methods/setUsername.js#L26) which is used for checking whether a username is valid or not: `^[0-9a-zA-Z-_.]+$`.
Actually, this is my fault -- I confused @polina-popova, having told her about some of my observations which I hadn't checked carefully.
